
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the Gadgeteer Designer.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports Gadgeteer
Imports GTM = Gadgeteer.Modules


Partial Public Class Program 
        Inherits Gadgeteer.Program

    ' GTM.Module definitions
    Private WithEvents led7r as Gadgeteer.Modules.GHIElectronics.LED7R
    Private WithEvents lightSensor as Gadgeteer.Modules.GHIElectronics.LightSensor
    Private WithEvents usbClientSP as Gadgeteer.Modules.GHIElectronics.UsbClientSP
    Private WithEvents button as Gadgeteer.Modules.GHIElectronics.Button

    Public Shared Sub Main()  
        'Important to initialize the Mainboard first
        Mainboard = New GHIElectronics.Gadgeteer.FEZCerberus()

        Dim program As Program = New Program()
        program.InitializeModules()
        program.ProgramStarted()
        program.Run() ' Starts Dispatcher

    End Sub

    Private Sub InitializeModules()
           
        ' Initialize GTM.Modules and event handlers here.		
        lightSensor = New GTM.GHIElectronics.LightSensor(3)
		
        button = New GTM.GHIElectronics.Button(4)
		
        led7r = New GTM.GHIElectronics.LED7R(7)
		
        usbClientSP = New GTM.GHIElectronics.UsbClientSP(8)

    End Sub
End Class

