
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the Gadgeteer Designer.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports Gadgeteer
Imports GTM = Gadgeteer.Modules


Partial Public Class Program 
        Inherits Gadgeteer.Program

    ' GTM.Module definitions
    Private WithEvents joystick as Gadgeteer.Modules.GHIElectronics.Joystick
    Private WithEvents oledDisplay as Gadgeteer.Modules.Seeed.OledDisplay
    Private WithEvents usbClientSP as Gadgeteer.Modules.GHIElectronics.UsbClientSP

    Public Shared Sub Main()  
        'Important to initialize the Mainboard first
        Mainboard = New GHIElectronics.Gadgeteer.FEZCerberus()

        Dim program As Program = New Program()
        program.InitializeModules()
        program.ProgramStarted()
        program.Run() ' Starts Dispatcher

    End Sub

    Private Sub InitializeModules()
           
        ' Initialize GTM.Modules and event handlers here.		
        joystick = New GTM.GHIElectronics.Joystick(4)
		
        oledDisplay = New GTM.Seeed.OledDisplay(5)
		
        usbClientSP = New GTM.GHIElectronics.UsbClientSP(8)

    End Sub
End Class

